module.exports = {
  purge: [
    './src/components/global/Header.vue',
    './src/components/global/Sidebar.vue',
    './src/components/global/Tabs.vue',
    './src/components/global/Table.vue',
    './src/components/global/Hint.vue',
    './src/components/global/Listbox.vue',
    './src/components/global/Loading.vue',
    './src/components/global/Modal.vue',
    './src/components/global/Switch.vue',
    './src/components/application/forums/TopicAudit.vue',
    './src/components/application/forums/TopicSetting.vue',
    './src/components/application/forums/ForumSetting.vue',
    './src/components/application/trade/BuyLog.vue',
    './src/components/application/trade/StoredLog.vue',
    './src/components/application/member/ExpertSetting.vue',
    './src/components/application/member/ManagerSetting.vue',
    './src/components/application/member/MemberSetting.vue',
    './src/components/application/advertise/TopAdvSetting.vue',
    './src/components/application/advertise/LeftAdvSetting.vue',
    './src/components/application/advertise/RightAdvSetting.vue',
    './src/components/application/advertise/FloatAdvSetting.vue',
    './src/components/application/channel/ChannelSetting.vue',
    './src/views/Home.vue',
    './src/views/Forum.vue',
    './src/views/Login.vue',
    './src/views/Trade.vue',
    './src/views/Member.vue',
    './src/views/Live.vue',
    './src/views/EMail.vue',
    './src/views/Advertise.vue',
    './src/views/forum/Forum.vue',
    './src/views/forum/Topic.vue',
    './src/views/channel/Channel.vue',
    './src/views/advertise/Advertise.vue',
    './src/views/member/Expert.vue',
    './src/views/member/Manger.vue',
    './src/views/member/Member.vue',
    './src/views/trade/TradeLog.vue',
    './src/App.vue',
  ],
  darkMode: 'class', //false or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        purple: {
          'main': '#C237E2',
          'main-70': 'rgba(194, 55, 226, .7)',
        },
        blue: {
          'main': '#4CA8F2',
          'gray': "#23384d",
          'modal': "#35526e",
          'gray-90': 'rgba(35, 56, 77, .90)',
          'gray-75': 'rgba(35, 56, 77, .75)',
          'gray-10': 'rgba(35, 56, 77, .10)',
          'light-10': 'rgba(219, 234, 254, .10)',
          'light-90': 'rgba(222, 222, 222, .90)'
        },
        gray: {
          'rice': '#ECE8E5',
          'tab': '#DFDFDE',
        },
        backdrop: '#00000060'
      },
      boxShadow: {
        'right': '15px 0px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)'
      },
      dropShadow: {
        'home-icon': '1px 1px 4px rgb(194, 55, 226)',
        'header-shadow-dark': '1px 1px 4px rgba(194, 55, 226, .7)',
        'header-shadow-light': '1px 1px 4px rgba(35, 56, 77, .7)',

      },
      borderRadius: {
        '4xl': '1.75rem',
        '5xl': '1.875rem',
      },
      inset: {
        '3px': '3px',
        '5px': '5px',
        '12px': '12px',
        '80px': '80px',
        '35rem': '0.35rem',
        '5%': '5%',
        '10%': '10%',
        '12.5%': '12.5%',
        '195px': '195px',
      },
      transitionDuration: {
        '5000': '5000ms',
      },
      minHeight: {
        '3/4': '75%'
      },
      padding: {
        '50px': '50px'
      },
      screens: {
        '992': '992px'
      },
      width: {
        '175px': '175px',
        '68px': '68px',
      },
      fontSize: {
        '11px': '11px'
      },
      zIndex: {
        '100' : 100
      },
      backgroundImage: theme => ({
        'login-dark-gradient': 'linear-gradient(#1f2937, #1f2937),radial-gradient(circle at top left, #fd00da, #19d7f8)',
        'login-gradient': 'linear-gradient(#DFDFDE, #DFDFDE),radial-gradient(circle at top left, #fd00da, #19d7f8)',
        'login-re-gradient': 'linear-gradient(#1f2937, #1f2937),radial-gradient(circle at top left, #19d7f8, #fd00da)',
        'btn-gradient': 'linear-gradient(#23374C, #23374C),radial-gradient(circle at top left, #fd00da, #19d7f8)',
      })
    },
  },
  variants: {
    accessibility: ['responsive', 'focus-within', 'focus'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    animation: ['responsive'],
    appearance: ['responsive'],
    backdropBlur: ['responsive'],
    backdropBrightness: ['responsive'],
    backdropContrast: ['responsive'],
    backdropDropShadow: ['responsive'],
    backdropFilter: ['responsive'],
    backdropGrayscale: ['responsive'],
    backdropHueRotate: ['responsive'],
    backdropInvert: ['responsive'],
    backdropSaturate: ['responsive'],
    backdropSepia: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundBlendMode: ['responsive'],
    backgroundClip: ['responsive'],
    backgroundColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus', 'disabled'],
    backgroundImage: ['responsive', 'focus-within', 'dark'],
    backgroundOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    backgroundOrigin: ['responsive'],
    blur: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
    borderOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxDecorationBreak: ['responsive'],
    boxShadow: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
    boxSizing: ['responsive'],
    brightness: ['responsive'],
    clear: ['responsive'],
    container: ['responsive'],
    contrast: ['responsive'],
    cursor: ['responsive', 'disabled'],
    display: ['responsive'],
    divideColor: ['responsive', 'dark'],
    divideOpacity: ['responsive', 'dark'],
    divideStyle: ['responsive'],
    divideWidth: ['responsive'],
    dropShadow: ['responsive', 'hover', 'dark'],
    fill: ['responsive'],
    filter: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: ['responsive'],
    fontStyle: ['responsive'],
    fontVariantNumeric: ['responsive'],
    fontWeight: ['responsive'],
    gap: ['responsive'],
    gradientColorStops: ['responsive', 'dark', 'hover', 'focus'],
    grayscale: ['responsive'],
    gridAutoColumns: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridAutoRows: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridColumnStart: ['responsive'],
    gridRow: ['responsive'],
    gridRowEnd: ['responsive'],
    gridRowStart: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridTemplateRows: ['responsive'],
    height: ['responsive'],
    hueRotate: ['responsive'],
    inset: ['responsive'],
    invert: ['responsive'],
    isolation: ['responsive'],
    justifyContent: ['responsive'],
    justifyItems: ['responsive'],
    justifySelf: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    mixBlendMode: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
    order: ['responsive'],
    outline: ['responsive', 'focus-within', 'focus', 'focus-visible'],
    overflow: ['responsive'],
    overscrollBehavior: ['responsive'],
    padding: ['responsive'],
    placeContent: ['responsive'],
    placeItems: ['responsive'],
    placeSelf: ['responsive'],
    placeholderColor: ['responsive', 'dark', 'focus'],
    placeholderOpacity: ['responsive', 'dark', 'focus'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    resize: ['responsive'],
    ringColor: ['responsive', 'dark', 'focus-within', 'focus'],
    ringOffsetColor: ['responsive', 'dark', 'focus-within', 'focus'],
    ringOffsetWidth: ['responsive', 'focus-within', 'focus'],
    ringOpacity: ['responsive', 'dark', 'focus-within', 'focus'],
    ringWidth: ['responsive', 'focus-within', 'focus'],
    rotate: ['responsive', 'hover', 'focus'],
    saturate: ['responsive'],
    scale: ['responsive', 'hover', 'focus'],
    sepia: ['responsive'],
    skew: ['responsive', 'hover', 'focus'],
    space: ['responsive'],
    stroke: ['responsive'],
    strokeWidth: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
    textDecoration: ['responsive', 'group-hover', 'focus-within', 'hover', 'focus'],
    textOpacity: ['responsive', 'dark', 'group-hover', 'focus-within', 'hover', 'focus'],
    textOverflow: ['responsive'],
    textTransform: ['responsive'],
    transform: ['responsive', "hover"],
    transformOrigin: ['responsive'],
    transitionDelay: ['responsive'],
    transitionDuration: ['responsive'],
    transitionProperty: ['responsive'],
    transitionTimingFunction: ['responsive'],
    translate: ['responsive', 'hover', 'focus'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive', 'focus', 'focus-within'],
    wordBreak: ['responsive'],
    zIndex: ['responsive', 'focus-within', 'focus']
  },
  plugins: [],
}
